### ISSUE TITLE
Stop Laravel Server

### ISSUE THREAD

**Issue by mexcoder** [TheColorRed/vscode-laravel-artisan#1]
after runing the command there server is started, but there is no further feedback and i cant find a way to stop it, not even closing vscode

**Comment by TheColorRed** [comment]
Laravel doesn't currently support stopping the server. I think I will have to look into adding some sort of hack to kill it.

Basically it is using php's built in server. http://php.net/manual/en/features.commandline.webserver.php

**Comment by TheColorRed** [comment]
I have fixed this issue. It will be in the next update.

The command `Artisan: Stop Server` has been added to the command palette.
