### ISSUE TITLE
The route cache could not be created

### ISSUE THREAD

**Issue by 4ern** [TheColorRed/vscode-laravel-artisan#10]
Hi, I get the following error.

![developer_tools_-_file____applications_visual_20studio_20code_app_contents_resources_app_out_vs_workbench_electron-browser_bootstrap_index_html_config__7b_22__22_3a_5b_5d_2c_22approot_22_3a_22_2fapplications_2fvisual_20studio_20code_app_2fc](https://user-images.githubusercontent.com/11194583/33201986-0599fd30-d0fb-11e7-8dbe-cecb2b3ced18.png)

But it works in the vscode terminal?

Thx for help

**Comment by TheColorRed** [comment]
What operating system are you using? I know it works in windows, I think there might be issues on other OS's

**Comment by TheColorRed** [comment]
I have updated the node_modules, it may fix the issue. I am able to run `route:list` on linux.

**Comment by 4ern** [comment]
I have this error on OSX. Where are you updated the node_modules?

**Comment by TheColorRed** [comment]
I updated the node_modules in the extension (you shouldn't have to do anything), which updated the vscode api. After updating to version `0.0.11` did this fix the issue for you?

I have tested it on Windows and Linux, and it works on both. Does it work for you on OSX? If not make sure node is up to date.

**Comment by 4ern** [comment]
I've updated node and have the latest version of this extension, yet I get the same error message.

**Comment by TheColorRed** [comment]
In your vscode output window, there should be a message that gets sent there. Could you check and see what it says? It should be prefixed with `[ERROR]` similar to this:

> [ERROR] Artisan's error message here

**Comment by 4ern** [comment]
The output window is empty. No error or anything else.
Another Screenshot from Developertools.
![developer_tools_-_file____applications_visual_20studio_20code_app_contents_resources_app_out_vs_workbench_electron-browser_bootstrap_index_html_config__7b_22__22_3a_5b_5d_2c_22approot_22_3a_22_2fapplications_2fvisual_20studio_20code_app_2fc](https://user-images.githubusercontent.com/11194583/33427588-0f21b166-d5c6-11e7-90d2-66bee938c319.png)
