### ISSUE TITLE
getting error after update

### ISSUE THREAD

**Issue by fatihdurmaz** [TheColorRed/vscode-laravel-artisan#100]
command 'artisan.make.model' not found

**Comment by TheColorRed** [comment]
The command is working for me, do you have an other information?

**Comment by cubNguyen** [comment]
Hi there,
I also get same error after update, the response is same with issue #90 ,

![image](https://user-images.githubusercontent.com/14900191/234522745-ffd7036f-eda6-42ec-8ce6-42f12137fd71.png)

**Comment by TheColorRed** [comment]
Thank you for the screen shot. I'll take a look today.

**Comment by pc-perrycima** [comment]
Same here. Not working after update.

**Comment by AlexDouglasUK** [comment]
Same issue with all commands

**Comment by TheColorRed** [comment]
I think the issues because I accidentally put rxjs in the "dev dependencies"  instead of the normal "dependencies"

**Comment by TheColorRed** [comment]
I have released an update that puts `rxjs` in the `dependencies`, once you receive the update `0.0.30`, please let me know if it is working for you.

**Comment by pc-perrycima** [comment]
Now working again. Thanks.
