### ISSUE TITLE
The "--views" option does not accept a value.  

### ISSUE THREAD

**Issue by tiansin** [TheColorRed/vscode-laravel-artisan#14]
Artisan:Run Command
make:auth

report this error:
[CMD] php "e:\xxxx\front/artisan" make:auth  --views= --force=
[ERROR] 
                                                 
  The "--views" option does not accept a value.

**Comment by TheColorRed** [comment]
I have written a fix for this. I should have it live within a day or two.

**Comment by TheColorRed** [comment]
I have realized that getting optional values is not set in in the command list when running `php artisan list --format=json`, so optional items will always get set.

**Comment by TheColorRed** [comment]
This has now been published, however, due to what is returned in `list --format=json` it isn't 100% implemented.

I will leave this issue open in hopes that it will be resolved on laravel's end and this can get finished up.

**Comment by Bricklou** [comment]
Problem always here with the command `php artisan serve` when I pass empty arguments.

![image](https://user-images.githubusercontent.com/15181236/57550905-f625aa00-7367-11e9-8b39-a30f551b9974.png)

![image](https://user-images.githubusercontent.com/15181236/57550947-0e95c480-7368-11e9-94c7-e69cd0f42417.png)

**Comment by TheColorRed** [comment]
@Bricklou You can try and use the command `Artisan: Start Server (Default Host and Port)`
