### ISSUE TITLE
Command to generate tests

### ISSUE THREAD

**Issue by Mecit** [TheColorRed/vscode-laravel-artisan#15]
This useful extension lacks the option to generate tests, so you have to switch to the terminal for that. It'd be nice to have a command for make:test.

**Comment by TheColorRed** [comment]
You can run `Artisan: Run Command` then `make:test`

**Comment by Mecit** [comment]
Ah, all right. I didn't know about it. I just tried that out but it keeps saying "Colud not run the command". Is this a general error or is it just on my end?

**Comment by TheColorRed** [comment]
It looks like it is the same issue that is happening from issue #14 it is trying to run

	php artisan make:test MyTest --unit=

With an error of

> The "--unit" option does not accept a value.

**Comment by TheColorRed** [comment]
I have added the command to generate tests

**Comment by TheColorRed** [comment]
This has now been published. Please open a new issue if you are having issues.

Thanks!

**Comment by Mecit** [comment]
Just tested it and it works fine. Thank you.
