### ISSUE TITLE
Not working on multi-root workspaces...

### ISSUE THREAD

**Issue by gbdematos** [TheColorRed/vscode-laravel-artisan#16]
...If the laravel workspace isn't the first one.

A setting to set the workspace to use would be awesome!

**Comment by TheColorRed** [comment]
I think the easiest way to do this would be to add a setting that can be set in the settings of the multi root workspace, it would look something like this:

```json
{
	"folders": [
		{
			"path": "C:\\Users\\user\\Documents\\workspaces\\workspace1"
		},
		{
			"path": "C:\\Users\\user\\Documents\\workspaces\\workspace2"
		}
	],
	"settings": {
		"artisan.location": "C:\\Users\\user\\Documents\\workspaces\\workspace2"
	}
}
```

As seen here the `artisan.location` keyword would set the path. It could either be a string or a number, in this case it would be `1` for a number indicating that it should use the 2nd item in the folders array.

**Comment by TheColorRed** [comment]
This has now been published. Please open a new issue if you are having issues.

Thanks!
