### ISSUE TITLE
Request: add "php artisan make:factory"

### ISSUE THREAD

**Issue by JeffBeltran** [TheColorRed/vscode-laravel-artisan#17]
unless i'm doing something wrong it looks like the the make factory command is missing but if i run artisan list:commands it shows up

**Comment by TheColorRed** [comment]
No, your not doing anything wrong. Each command was hand coded to ask specific questions about the command you want to run. That command was not coded that way. However, for now, you can do `Artisan: Run Command` and select `make:factory` and answer the standard questions in there.

**Comment by JeffBeltran** [comment]
simple enough, thanks

**Comment by TheColorRed** [comment]
I have created a new command that will now allow you to create a factory the same way as other items.

	Artisan: Make Factory
		Q1: Factory Name
		Q2: Is there a related model
		Q3: If yes what is it called
