### ISSUE TITLE
artisan.migrate.fresh twice

### ISSUE THREAD

**Issue by hanc2006** [TheColorRed/vscode-laravel-artisan#19]
The command **artisan.migrate.fresh**  Is declared twice in the commands section on **package.json**
 and vscode report it.

`
{
                "command": "artisan.migrate.fresh",
                "title": "Artisan: Migrate Fresh"
},
`

Thx

**Comment by TheColorRed** [comment]
Thanks for the find! Does the command still work properly?

**Comment by hanc2006** [comment]
yes

**Comment by TheColorRed** [comment]
This fix has been published.
