### ISSUE TITLE
i can't use any artisan command

### ISSUE THREAD

**Issue by jarjut** [TheColorRed/vscode-laravel-artisan#22]
every time i use any artisan command from this extension, always failed.

![capture](https://user-images.githubusercontent.com/24451652/39092001-55708aa8-462c-11e8-8dfc-8e7274895d8b.JPG)

**Comment by TheColorRed** [comment]
If you go to the output console, and select `Laravel Artisan` from the drop down menu, what messages are displayed there?

**Comment by jarjut** [comment]
`[CMD] php artisan route:list`
`[ERROR] Could not open input file: artisan`

**Comment by jarjut** [comment]
the **artisan** file exist, i can run **artisan** command normally through terminal. the file permission is ok

**Comment by ChacMaster** [comment]
Is the same message that apears to me on #21 .

@jarjut
you are running on windows? i
f yes, where's located your project? in which unit (C: \, D: \, etc ...)?

**Comment by jarjut** [comment]
yes I'm having the same problem.

i am running on windows and my project in disk D:
