### ISSUE TITLE
No Errors Shown in case of Command Fail

### ISSUE THREAD

**Issue by alidhillon** [TheColorRed/vscode-laravel-artisan#28]
Where to see the output of command. If the command succeed then all is good but if command fails how to see the errors in this extension.
When command Fail box show up it should reference to an error page.

**Comment by TheColorRed** [comment]
Commands can be seen in the output window `Ctrl+Shift+U`:

```
View -> Output
```

Once the window has opened, on the right hand side there is a drop down menu. Within that menu select `Laravel Artisan`. Within that window, you will now see all the commands that were executed, and any errors that were generated.

**Comment by alidhillon** [comment]
Thanks very much. Every time a command fails I have to run it in Terminal to see the error.
