### ISSUE TITLE
WSL php support?

### ISSUE THREAD

**Issue by heihachi88** [TheColorRed/vscode-laravel-artisan#29]
I'm using PHP inside WSL, also VSCode terminal is setup using `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\wsl.exe",`

So none of artisan commands not launching using this extension, due to missing php or paths (VSCode installed in WIndows, PHP installed in WSL)

In integrated terminal artisan commands works well.

Console output:

```
[CMD] php artisan route:list
[ERROR] 
[CMD] php artisan make:command ads --command=asd
[ERROR] 
[CMD] php artisan route:list
[ERROR] 
[CMD] php artisan cache:clear  
[ERROR] 
[CMD] php artisan make:controller TestController --resource
[ERROR] 
```

**Comment by TheColorRed** [comment]
Have you tried adding the path to php in your environment variables?

For example:

```
C:/Users/<username>/AppData/Local/lxss/rootfs/usr/bin
```

See this post for the location of your WSL root file system:

https://askubuntu.com/questions/759880/where-is-the-ubuntu-file-system-root-directory-in-windows-subsystem-for-linux-an/759885#759885

**Comment by heihachi88** [comment]
`"artisan.location": "C:\\Users\\<username>\\AppData\\Local\\lxss\\rootfs\\usr\\bin"`

Not working, same behavior.

**Comment by TheColorRed** [comment]
Did you replace `<username>` with the actual user, and did you make sure your WSL is located under `lxss`?

**Comment by heihachi88** [comment]
Changed name, but path is wrong. Root cause of this issue because of wrong path? I mean VSCode can't read WSL path?

**Comment by TheColorRed** [comment]
Did you add:

```
C:\\Users\\Alexander\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\\LocalState\\rootfs\\usr\\bin
```

To the system environment variables, then restart VSCode?

**Comment by heihachi88** [comment]
You mean Windows environment variables? Which one? PATH?

**Comment by TheColorRed** [comment]
yeah, the `Path` variable. Probably want to modify the one in the section `User variables for Alexander`

**Comment by heihachi88** [comment]
Bro, it didn't work. I even rebooted my PC. Maybe you could do something on the plugin side?

**Comment by TheColorRed** [comment]
I think what I will have to do is add a user setting for a custom php location. This may or may not work though, as I am not sure how else I would handle WSL.

Give this a try. The setting is  `artisan.php.location` something like this:

```
{
  artisan.php.location": "C:\\path\\to\\wsl\\path\\to\\php
}
```

[laravel-artisan-0.0.22.vsix.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/2271489/laravel-artisan-0.0.22.vsix.zip)

**Comment by heihachi88** [comment]
Do i need to delete previous setting? ...rootfs\\usr\\bin?

**Comment by TheColorRed** [comment]
`artisan.location` is the location of artisan, not php. This setting isn't use too much, it currently is only used to open a file in the editor, and will eventually be removed.

So if the file `artisan` is in your workspace root, that setting can be removed.

**Comment by heihachi88** [comment]
0.0.22 worked for me, thanks! Problem was in php path.

**Comment by aalaap** [comment]
It doesn't work for me.

```
    {
        "artisan.php.location": "C:\\Users\\Aalaap\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState\\rootfs\\usr\\bin\\php7"
    }
```

```
[CMD] "C:\\Users\\Aalaap\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState\\rootfs\\usr\\bin\\php7" artisan route:list
[ERR] Command failed: cd /d "c:\Users\Aalaap\Documents\www\html\communitees" && "C:\\Users\\Aalaap\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState\\rootfs\\usr\\bin\\php7" artisan route:list
'"C:\\Users\\Aalaap\\AppData\\Local\\Packages\\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\\LocalState\\rootfs\\usr\\bin\\php7"' is not recognized as an internal or external command,
operable program or batch file.```
