### ISSUE TITLE
Could not get the status of the migrations

### ISSUE THREAD

**Issue by heinzin** [TheColorRed/vscode-laravel-artisan#3]
firstly ,
I can use your extension is so nice and easy ,
but later,
I can't use anything commands of artisan .

always showing error ,error,error -_-

I am running on laravel 5.5 dev and PHP 7.1.7-1+ubuntu16.10.1+deb.sury.org+1 (cli)
vscode latest version

even newly laravel stable version and test your extension 
but still error ..

I tested again 
if I migrate refresh and ask me your extension
what database should I use ?
I typed my database name and Should I seed the database for you? yes
but result is error .  not worked db seeding..

I typed just enter and should I seed the database for you? yes
but result is okay. worked db seeding..
 
> Not working if I input the db name .

**Comment by heinzin** [comment]
even newly laravel installation with laravel stable version
and test your extension 
still error

**Comment by TheColorRed** [comment]
Do you have an example Artisan project I can test with?

**Comment by heinzin** [comment]
I don't have artisan project .
I just installed the vscode extension 
uninstalled and reinstall 
but not work 
asked " what database should I use ?"
if I input the db name , not working migration commands.
but work fine without db name . migration commands

**Comment by heinzin** [comment]
Manually in terminal
>php artisan migrate:status --database=dbname -vvv

  [InvalidArgumentException]
  Database [job] not configured.

**Comment by heinzin** [comment]
sorry bro that my bad 
I miss understandard 
that "what database should I use ?"
It mean database types e.g mysql,sqlite,redis,etc....
## Not Database Name

**Comment by TheColorRed** [comment]
when it asks for a database, it is asking for this: `--database=dbname` in your case it would be `dbname`

You need to have the database configured in laravel for this to work, so for example:

```php
<?php
return [
    'connections' => [
		'dbname' => [
			'driver'    => 'mysql',
			'host'      => env('DB_HOST', '127.0.0.1'),
			'port'	    => env('DB_PORT', '3306'),
			'database'  => env('DB_DATABASE'),
			'username'  => env('DB_USERNAME'),
			'password'  => env('DB_PASSWORD'),
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'strict'    => false,
		]
    ]
]
```

This is according to `php artisan migrate:status -h` which outputs:

```
Usage:
  migrate:status [options]

Options:
      --database[=DATABASE]  The database connection to use.
      --path[=PATH]          The path of migrations files to use.
  -h, --help                 Display this help message
  -q, --quiet                Do not output any message
  -V, --version              Display this application version
      --ansi                 Force ANSI output
      --no-ansi              Disable ANSI output
  -n, --no-interaction       Do not ask any interactive question
      --env[=ENV]            The environment the command should run under.
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for
 more verbose output and 3 for debug

Help:
 Show the status of each migration
```
