### ISSUE TITLE
Homestead development

### ISSUE THREAD

**Issue by novack96** [TheColorRed/vscode-laravel-artisan#30]
Hello!

I'd like to ask if there is any way to use this extension with Homestead properly? If I use the Config Cache or Config Refresh artisan command, my application always shows an UnexpectedValueException Protocol Error exception whenever I try to load a page. I assumed that happens because the command will need to be executed inside the VM. Well. of course, I could execute `php artisan config:cache` manually via SSH, but I'd rather use this extension.
So there is any way to call into play this ext, or I have to manually modify the source code? 😄 

Thanks for everyone for the answer in advance!

**Comment by TheColorRed** [comment]
I have made some updates to the extension. You can now add these additional settings:

1. Set a custom php location, example: 
    * `"artisan.php.location": "/path/to/php.exe"`
2. Added addition artisan path settings, examples: 
    * `"artisan.location": ["/path1/artisan", "/path2/artisan"]`
    * `"artisan.location": "/path/artisan"`

Try setting them with this update and let me know if it works for you:

[laravel-artisan-0.0.22.vsix.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/2303289/laravel-artisan-0.0.22.vsix.zip)

**Comment by novack96** [comment]
I cannot tell the extesnion with these settings for example SSH-ing to the VM and run the command inside the VM, or something like that. I didn't have a second artisan file

**Comment by yakushenkovpaul** [comment]
Hi, i try to work with you extension, but i cant, because i always get errors... For example, if i write: Artisan Command List, i get: Couldnt get the list, the fields "artisan.php.location" and "artisan.location" arent empty

**Comment by yakushenkovpaul** [comment]
and i made your last update: laravel-artisan-0.0.22.vsix.zip
