### ISSUE TITLE
Artisan selection dropdown re-opens by itself

### ISSUE THREAD

**Issue by geoffwasham** [TheColorRed/vscode-laravel-artisan#31]
Any time I try to use the Artisan command through this, the selection dropdown re-opens itself a few seconds later, and doing anything to make it go away clears the routes list when that is opened.

Steps: CMD+SHIFT+P, type/select Artisan:Route List, select which artisan to use, (route list appears), a few moments later select list drops down again/will not go away

**Comment by TheColorRed** [comment]
This has been published, let me know if you have any issues.
