### ISSUE TITLE
New Options on Make Controller

### ISSUE THREAD

**Issue by ChacMaster** [TheColorRed/vscode-laravel-artisan#32]
Helo There,

I recently begins to work with API only project on Laravel, using the plugin, i can't create the model (Artisan: Make Model) with the option "resource", because in the API, has two less methods in the controller. 

I can't use the create controller (Artisan: Create Controller) either, because he only asks if the model is a resource, if i say YES, he create the controller with the two methods i don't want.

I think you can add some option on the Create Controller to ask if the controller is a API RESOURCE, like the actual.

![captura de tela 2018-10-12 as 00 06 01](https://user-images.githubusercontent.com/1786995/46845682-cfdc6380-cdb2-11e8-800a-2db5515ae934.png)

If i ask NO to the above questions, show the question "Should i make this a API RESOURCE controller?"

In the command generated the change is only in the place of "--resource" , is "--api".

Plus you can add a final question to add a model to the controller, a question like the name, where user can insert some name on it. The changes on the command is add at the end "--model MyModel".

By the way, congrats for this awesome plugin, helps a lot in day by day.

Regards

**Comment by TheColorRed** [comment]
I have changed the question for creating a resource to be as follows:

* What type of controller is this?
  * Basic
  * Resource
  * API

Next it now asks if it should reference a model (if it is not a basic controller), then asks for which model to reference. If the model doesn't exist it will create it.

Please test this package and let me know if this works for you and your needs:

[laravel-artisan-0.0.23.vsix.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/2473823/laravel-artisan-0.0.23.vsix.zip)

Thanks

**Comment by TheColorRed** [comment]
This has been published to the marketplace!
