### ISSUE TITLE
stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by xiomai** [TheColorRed/vscode-laravel-artisan#38]
```
[CMD] "php" artisan route:list
[ERR] stdout maxBuffer length exceeded
```
I am not sure how to reproduce this or this is specific to this extension but is there a fix for this?
I can successfully route:list on command line but not on this extension which is very helpful.

**Comment by TheColorRed** [comment]
Okay thank you, It looks like it is a fixable nodejs issue. By default nodejs only outputs `200KB` to the buffer, so that must mean you have lots of routes; is that assumption correct?

I can add an option to increase the buffer size for larger projects.

**Comment by xiomai** [comment]
Yes I have a lot of routes since it also includes my api routes.

Is there a way to increase the `200kb` limit in the meantime?
Sorry I know this is not part of your extension but i've been googling and i can't get a definitive solution.

**Comment by TheColorRed** [comment]
Please give this a try. In your settings increase the `maxBuffer` setting to something of your choosing. The number value is in bytes.

Please let me know if this works for you thanks!

[laravel-artisan-0.0.25.vsix.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/2861171/laravel-artisan-0.0.25.vsix.zip)

**Comment by xiomai** [comment]
Yes it works. thanks a lot!
