### ISSUE TITLE
Routes List action fields open file to referenced method

### ISSUE THREAD

**Issue by geoffwasham** [TheColorRed/vscode-laravel-artisan#39]
Please make the action field contents (which already look like a hyperlink) work on click to open the referenced file at the referenced method.

Thanks for the extension, awesome work!

**Comment by TheColorRed** [comment]
The links are supposed to open the file when clicked, there must be a bug somewhere upon click...

**Comment by TheColorRed** [comment]
![Click Link Laravel Artisan](https://user-images.githubusercontent.com/1571806/55828858-f6b1f300-5ad2-11e9-803f-edd3dc9995f4.gif)

**Comment by geoffwasham** [comment]
I just updated VS Code and uninstalled/reinstalled vscode-laravel-artisan. Unfortunately, it still seems bugged for me. When I click on the link, it just highlights. Right-click does nothing either. In case it matters, I'm on a Mac, running Mojave.

**Comment by lidroid** [comment]
> I just updated VS Code and uninstalled/reinstalled vscode-laravel-artisan. Unfortunately, it still seems bugged for me. When I click on the link, it just highlights. Right-click does nothing either. In case it matters, I'm on a Mac, running Mojave.

me too

**Comment by TheColorRed** [comment]
It looks like **Mac** and **Linux** require a triple slash for `file:///` whereas windows accepts two `file://`

Give this a try and let me know if it works:

[laravel-artisan-0.0.26.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/3169190/laravel-artisan-0.0.26.zip)

**Comment by TheColorRed** [comment]
Forgot to publish this, but it has now been published.
