### ISSUE TITLE
Request: add "php artisan make:auth"

### ISSUE THREAD

**Issue by carpad88** [TheColorRed/vscode-laravel-artisan#42]
It would be great to add the command "php artisan make:auth"

**Comment by TheColorRed** [comment]
Give this a try:

[laravel-artisan-0.0.26.vsix.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/3336718/laravel-artisan-0.0.26.vsix.zip)

**Comment by carpad88** [comment]
Thank's a lot, that made the trick. 

I think it should be out of the box with the vscode extension. I didn't realize that it wasn't until I have to apply the command and I never found it

**Comment by TheColorRed** [comment]
Forgot to publish this, but it has now been published.
