### ISSUE TITLE
Laravel 4.2 support

### ISSUE THREAD

**Issue by DanielDK100** [TheColorRed/vscode-laravel-artisan#46]
Since the artisan commands differ when using an older Laravel version (in this case 4.2), the extension's commands fail when executed (for instance, https://laravel.com/docs/4.2/migrations).

Maybe Laravel 4.2 support should be added since legacy systems still depend on older versions of Laravel.

**Comment by TheColorRed** [comment]
These commands may still be able to be executed through:

<kbd>F1</kbd> > `Artisan: Run Command` > `command:name`

**Comment by danielwinther** [comment]
I'm well aware of this, however I might as well use the terminal for those commands instead of this plugin, hence why it would be benificial to have those commands integrated in the plugin itself.
