### ISSUE TITLE
Problem on "Artisan Start Server" default host and port

### ISSUE THREAD

**Issue by alaminfirdows** [TheColorRed/vscode-laravel-artisan#48]
When I try to start the laravel project by "Artisan Start Server" default host and port it produces an incompleted command.

Like ```php "{location}" serve --host='localhost --port='8000```

![image](https://user-images.githubusercontent.com/30468274/66551733-dd652e80-eb69-11e9-8e23-754f0ebcf82e.png)

**Comment by alaminfirdows** [comment]
I've fixed it.
![image](https://user-images.githubusercontent.com/30468274/66552779-bd366f00-eb6b-11e9-82b8-ad2f0bc8c2c4.png)

**Comment by NariyasuHeseri** [comment]
> I've fixed it.
> ![image](https://user-images.githubusercontent.com/30468274/66552779-bd366f00-eb6b-11e9-82b8-ad2f0bc8c2c4.png)

Great! Why not open a pull request?

**Comment by alaminfirdows** [comment]
> > I've fixed it.
> > ![image](https://user-images.githubusercontent.com/30468274/66552779-bd366f00-eb6b-11e9-82b8-ad2f0bc8c2c4.png)
> 
> Great! Why not open a pull request?

I am going to create it. Thanks.

**Comment by TheColorRed** [comment]
Duplicate of #47
