### ISSUE TITLE
Artisan commands are not running in VS Code

### ISSUE THREAD

**Issue by Dimonka2** [TheColorRed/vscode-laravel-artisan#51]
I am running a simple code from VSCode and getting following error:

> [CMD] "php" artisan make:policy EmailPolicy --model=Email
[ERR] Command failed: cd /d "c:\laragon\www\zzz" && "php" artisan make:policy EmailPolicy --model=Email
'"php"' is not recognized as an internal or external command,
operable program or batch file. 

If I copy/paste and run the same command via command line - it runs without any problems. 

VSCode 1.40.1, Win10 x64

**Comment by Dimonka2** [comment]
This issue looks like a general problem of the terminal inside VSCode. Terminal inside VSCode just does not see PHP. Outside VSCode everything works ok.

**Comment by TheColorRed** [comment]
It's most likely that vscode is reading the wrong $PATH data in the terminal.
