### ISSUE TITLE
Lacks make:rule command

### ISSUE THREAD

**Issue by nomadbard916** [TheColorRed/vscode-laravel-artisan#52]
This command is very useful for creating customized validation rules starting Laravel 5.5, which fact I figured out when watching "Let's Build A Forum with Laravel and TDD" on Laracasts.
However this useful command is still missing in this wonderful extension (yeah I almost threw terminal after this extension was installed haha). It'd be sweet if the author adds the command in next version ;)

**Comment by TheColorRed** [comment]
You can make a rule using **Run Command**:

<kbd>F1</kbd> > `Artisan: Run Command` > `make:rule`

**Comment by nomadbard916** [comment]
@TheColorRed  Thank you so much!
