### ISSUE TITLE
can't use Custom Commands

### ISSUE THREAD

**Issue by 2896726646** [TheColorRed/vscode-laravel-artisan#53]
[CMD] "php" artisan list --format=json
[ERR] stdout maxBuffer length exceeded

**Comment by 2896726646** [comment]
like phpstorm command line, autocomplete artisan command

**Comment by TheColorRed** [comment]
The buffer size can be changed in the settings, where the buffer is in bytes:

```
{
  "artisan.maxBuffer": 204800
}
```

**Comment by 2896726646** [comment]
custom commands
can't use options
