### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Atash01** [TheColorRed/vscode-laravel-artisan#55]
- Issue Type: `Bug`
- Extension Name: `laravel-artisan`
- Extension Version: `0.0.27`
- OS Version: `Windows_NT ia32 10.0.17763`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by TheColorRed** [comment]
Without the data we cannot resolve this issue. Please add the attached data.
