### ISSUE TITLE
Test Stub

### ISSUE THREAD

**Issue by scottzirkel** [TheColorRed/vscode-laravel-artisan#57]
When I generate a test it extends an unexpected `TestCase`. It pulls in `PHPUnit\Framework\TestCase` when it the artisan command uses `Tests\TestCase` by default. Any way to update that in the configs?

**Comment by TheColorRed** [comment]
This file is generated by Artisan and not the extension.

**Comment by scottzirkel** [comment]
Ah, the unit tests from the artisan command are pulling in the different TestCase. Thanks.
