### ISSUE TITLE
replace $table->id(); with $table->bigIncrements('id');

### ISSUE THREAD

**Issue by sergeByishimo** [TheColorRed/vscode-laravel-artisan#58]
Good Package!

As you may have known, laravel changed it's default migration primary key ` $table-id()` with 
`$table->bigIncrements('id')`   so it would be appropriate for this extension to use that as well.
thanks.

**Comment by TheColorRed** [comment]
I am not sure I understand what you are asking. This extension does not generate or modify files. Could you please explain what you mean otherwise I will need to close this as out of scope.

**Comment by sergeByishimo** [comment]
Oooh sorry i didnt realize that it doesnt generate files. thanks for the feedback!

**Comment by TheColorRed** [comment]
No problem! You might want to create an issue with Laravel Artisan to address this.

**Comment by sergeByishimo** [comment]
Not necessary, i though it was your side choosing to use `$table->id()` when you created migration files but its not, so no problem at all.
