### ISSUE TITLE
stdout maxBuffer length exceeded when selecting route list

### ISSUE THREAD

**Issue by pratamatama** [TheColorRed/vscode-laravel-artisan#68]
Hi, first of all, I want to say thanks for developing this extension. It helped me a lot in past few years until present.
Today, I have some issue that prevents me from listing out routes.

Doing `php artisan route:list` manually works fine, but when I try to use this package to open it on new tab in VS Code, it throws this error:

```
[ERR] Command failed: cd "/Users/warmachine/Documents/Programming/Laravel/secret/" && "php" artisan route:list
[CMD] "php" artisan route:list
[ERR] stdout maxBuffer length exceeded
[CMD] "php" artisan route:list
[ERR] stdout maxBuffer length exceeded
```

Not sure wether it was a bug from the package or VS Code itself. Any thought?

OS build: Mac OS Catalina (Latest)
VS Code version: 1.49.0
Extension version: v0.0.27

**Comment by TheColorRed** [comment]
You need to increase the size of the buffer. There is a setting you can set:

`artisan.maxBufferSize`

I am closing this issue. If you are still having problems you can reopen it.

Thanks for the support!

**Comment by cognitus** [comment]
@TheColorRed Add to Readme, please

**Comment by shlomo-shalev** [comment]
I managed to fix the maxBuffer problem but now it can't show me the list commands:

<img width="1541" height="953" alt="Image" src="https://github.com/user-attachments/assets/ac386afb-1531-46a5-a2d4-1597aed9dc29" />

the response of "php artisan list --format=json" returns but the page doesn't change.
