### ISSUE TITLE
Route:list shows "stdout maxBuffer length exceeded" on fresh Laravel 8 project with Jetstream

### ISSUE THREAD

**Issue by fylzero** [TheColorRed/vscode-laravel-artisan#69]
When I install a fresh copy of Laravel 8 with Jetstream / Inertia and try to use the plugin to view route:list my console outputs "Route:list shows "stdout maxBuffer length exceeded" on fresh ravel 8 project with Jetstream"

I'm assuming this has to do with how the output is displaying all of the middleware.

Might need a config option to increase the maxBuffer, whatever that is referring to...  or possibly consider only displaying the compact list?  idk

Not having this really is slowing down my workflow.

**Comment by TheColorRed** [comment]
Duplicate of https://github.com/TheColorRed/vscode-laravel-artisan/issues/68
