### ISSUE TITLE
Route List: Search query clears when switching tabs

### ISSUE THREAD

**Issue by Jarvl** [TheColorRed/vscode-laravel-artisan#7]
Title pretty much sums it up. When there is a search term in the search box, if I switch to another tab then back to the route list tab, the search query will be empty.

**Comment by TheColorRed** [comment]
This is a vscode issue if I am not mistaken.

**Comment by jm-mwi** [comment]
Would there be a way to detect when it gains focus and simply rerun the command to generate the page?

**Comment by TheColorRed** [comment]
That might be feasible, I think if I just store the query string in a var, then repopulate the input box on re-focus that could work.

**Comment by TheColorRed** [comment]
This issue is logged with Microsoft here: https://github.com/Microsoft/vscode/issues/36310

**Comment by TheColorRed** [comment]
This has now been published to the market, along with addition features:

- Preserve the web views: `Route List`, `List Commands`, `Migrate Status` using the new WebView API.
  - This will allow for navigation away from, and then back to the tab without reloading the web view.
- `Route List` will automatically update when routes are added/removed/updated.
- When clicking on a `Route List` route, the document will open and the cursor will move to the line where the function is defined.

Let me know if you have any issues
