### ISSUE TITLE
Configure the route:list feature to not display middleware.  Laravel 8 displays too much middleware with Jetstream.

### ISSUE THREAD

**Issue by fylzero** [TheColorRed/vscode-laravel-artisan#70]
Fresh Laravel 8 project with Jetstream / Inertia displays tons of inline middleware and makes this feature fairly useless.  Anything that can be done about it would be super appreciated.  Is there a way to configure this page to output the compact route:list without middleware being displayed?

![Route_List_—_deskninja](https://user-images.githubusercontent.com/3542501/93928158-80fa1100-fcdf-11ea-975a-5b9db7bc3ee6.png)

**Comment by TheColorRed** [comment]
This will be in the next upcoming release.

**Comment by TheColorRed** [comment]
This has been released into `0.0.31` Along with other route list features:

![image](https://user-images.githubusercontent.com/1571806/234890310-d66b60be-fbd3-4842-9c6a-8f1e0b8427a8.png)
