### ISSUE TITLE
Command 'Artisan: Optimize' resulted in an error (command 'artisan.optimize' not found)

### ISSUE THREAD

**Issue by developcreativo** [TheColorRed/vscode-laravel-artisan#76]
`Command 'Artisan: Optimize' resulted in an error (command 'artisan.optimize' not found)`
Windows 10
Laragon
![image](https://user-images.githubusercontent.com/5873347/110123474-4f5d9980-7d97-11eb-9248-1e529cc58bfe.png)

**Comment by DanielBUBU** [comment]
Having same issue with different commands in VS code.
![image](https://user-images.githubusercontent.com/54381631/116425521-ed8c4e00-a874-11eb-8417-31f0a2bd1301.png)

**Comment by sunil19822701** [comment]
Having same issue on 
VsCode ver : 1.63.1
Os : Windows 10

But after disabling and reenabling extension it works again till vscode is restarted

**Comment by fahmiegerton** [comment]
Got the same problem. Few days ago was just fine, now any command is just doesn't work. Rolling back to old version is also doesn't work.
![image](https://user-images.githubusercontent.com/5303871/147478275-69b6b509-510b-42be-b85b-8c15bdc087d9.png)

VS Code vers. : 1.63.2
OS : Windows 10 Home
Extension vers. : 0.0.28

**Comment by fahmiegerton** [comment]
Sometimes it works sometimes it doesn't. I don't know if this bug from vscode, this extension or something I may misconfigure. But today I got this error and I don't know how to fix it.
![image](https://user-images.githubusercontent.com/5303871/147798308-055d1d38-1b05-4740-90d2-56eca25c1648.png)

**Comment by afrizal423** [comment]
You just uninstall then install again.
windows 10
vscode 1.66.2

**Comment by TheColorRed** [comment]
This seems to be working.
