### ISSUE TITLE
Space in project/artisan path

### ISSUE THREAD

**Issue by gbdematos** [TheColorRed/vscode-laravel-artisan#8]
I get the following error when trying any command:

```
[CMD] php d:\Dropbox\Project X\backend/artisan make:controller Test --resource
[ERROR] Could not open input file: d:\Dropbox\Project
```

**Comment by TheColorRed** [comment]
Thank  you, it looks like the artisan path should have quotes around it.

**Comment by TheColorRed** [comment]
I have created a fix, I just need to test it on Windows before putting it live due to windows using `\` instead of `/`. I am not sure if it will escape the next char or not.

**Comment by TheColorRed** [comment]
@gbdematos I have updated the extension, please git it a try now. Let me know if you have any more issues.

Thanks

**Comment by gbdematos** [comment]
@TheColorRed It's working flawlessly. Awesome, thanks!
