### ISSUE TITLE
Add sail compatibility

### ISSUE THREAD

**Issue by adammpkins** [TheColorRed/vscode-laravel-artisan#88]
I don't seem to be able to run these commands from sail. You may know that sail uses the syntax: sail artisan <command>

but there doesn't seem to be an option to enable that option or integrate with sail otherwise.

**Comment by sasaorasanin** [comment]
@adammpkins you could edit settings for:

**Sets a custom location to the php executable** as sail

However that only wont work because it uses it as a string so it will fail, maybe if there is a eval "sail" it would work.

**Comment by aska-kaneda** [comment]
I know it's been a long time and it may have already been resolved.
I will record this for the benefit of those who visit here.

I was able to execute the command with the following configuration
` "artisan.docker.command": "docker-compose exec -T -u sail 'laravel.test'",`

**Comment by chWagnr** [comment]
I just set `"artisan.docker.command": "./vendor/bin/sail"`
