### ISSUE TITLE
Suppoprt the new Laravel 9 artisan route:list command

### ISSUE THREAD

**Issue by ajcastro** [TheColorRed/vscode-laravel-artisan#89]
It doesn't look good in the new Laravel 9. 
![image](https://user-images.githubusercontent.com/4918318/154612469-4b3af791-266f-4173-b42d-8126a9e47e99.png)

@TheColorRed, do you have plans to support the Laravel 9 route:list command? 
I am thinking maybe utilize the `--json` flags so it will be both compatible Laravel 8 and Laravel 9. What do you think?
Thanks!

Related: https://github.com/laravel/framework/discussions/41090

**Comment by TheColorRed** [comment]
This has been released. Let me know if this works or not.
