### ISSUE TITLE
Run Custom Command

### ISSUE THREAD

**Issue by sineld** [TheColorRed/vscode-laravel-artisan#9]
Please add support to run custom Artisan commands.

For me I use:

`php artisan renew:app`

Thanks.

**Comment by TheColorRed** [comment]
One of the main issues would be how to know what options come with custom commands?

I believe that I can get a list of commands returned as json, so, I still need to look at the list to see how it is formatted. If I can get a list of options I can go that route otherwise I need to figure out a different way to approach it.

**Comment by TheColorRed** [comment]
I have added this feature, if you could test it out, and let me know what you think that would be great.

* Command: `Artisan: Run Command`

[laravel-artisan-0.0.11.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/1497150/laravel-artisan-0.0.11.zip)

**Comment by sineld** [comment]
@TheColorRed I installed it. It runs the command no problem but it does not print / echo anything.

My sample command ends with
`$this->info('Application successfully renewed.');`
but nothing printed out.

**Comment by TheColorRed** [comment]
@sineld I have added output, it should write to the Output Console, you can test the results with this update:

[laravel-artisan-0.0.11.zip](https://github.com/TheColorRed/vscode-laravel-artisan/files/1497464/laravel-artisan-0.0.11.zip)

**Comment by sineld** [comment]
@TheColorRed I only see
`[CMD] php "/Users/sineld/Code/project/artisan" renew`
in output.

**Comment by sineld** [comment]
@TheColorRed Sorry my bad,
I can now see
`Command "renew" has finished (See output console for more information)`
on the top and
`Application successfully renewed in 6.32 seconds.` in the output screen.
You have done well.

**Comment by TheColorRed** [comment]
@sineld if you (or anyone else) has projects with commands that have arguments/options, it would be helpful if those commands could be tested.

Thanks!

**Comment by TheColorRed** [comment]
This has now been published.
