### ISSUE TITLE
Error command 'artisan.make.middleware' not found

### ISSUE THREAD

**Issue by developcreativo** [TheColorRed/vscode-laravel-artisan#90]
![image](https://user-images.githubusercontent.com/5873347/165284101-454aa0ec-21f0-493a-9bc2-5d325f9b5b20.png)
![image](https://user-images.githubusercontent.com/5873347/165284352-6dfc5799-b149-4288-b392-e36ad51ea59a.png)
![image](https://user-images.githubusercontent.com/5873347/165284421-279ae595-4710-4bcc-8c79-80c7478d2bd8.png)

**Comment by TheColorRed** [comment]
Is this still an issue?
